### ISSUE TITLE
Bug: auto approve action failed

### ISSUE THREAD

**Issue by MaikoTan** [AwesomeHamster/koishi-plugin-ffxiv-macrodict#27]
Broken after #25 merged, error message see: https://github.com/AwesomeHamster/koishi-plugin-ffxiv-macrodict/actions/runs/3034416379

Looks like you missed the reference in the `uses` option, which should be a form as `owner/repo@ref`
https://github.com/AwesomeHamster/koishi-plugin-ffxiv-macrodict/blob/b9c47f2e2a2178bbfb0724a669feda0fca890a09/.github/workflows/auto-approve.yml#L12

Should be `AwesomeHamster/actions-auto-approve@master`

**Comment by SaarChaffee** [comment]
> Broken after #25 merged, error message see: https://github.com/AwesomeHamster/koishi-plugin-ffxiv-macrodict/actions/runs/3034416379
> 
> Looks like you missed the reference in the `uses` option, which should be a form as `owner/repo@ref`
> 
> https://github.com/AwesomeHamster/koishi-plugin-ffxiv-macrodict/blob/b9c47f2e2a2178bbfb0724a669feda0fca890a09/.github/workflows/auto-approve.yml#L12
> 
> Should be `AwesomeHamster/actions-auto-approve@master`

https://github.com/AwesomeHamster/lodestone-news/blob/master/.github/workflows/auto-approve.yml#L11

**Comment by MaikoTan** [comment]
> [https://github.com/AwesomeHamster/lodestone-news/blob/master/.github/workflows/auto-approve.yml#L11](https://github.com/AwesomeHamster/lodestone-news/blob/master/.github/workflows/auto-approve.yml?rgh-link-date=2022-09-13T03%3A05%3A27Z#L11)

Looks like should you fire an issue in that repository either. >_<

**Comment by SaarChaffee** [comment]
> > [https://github.com/AwesomeHamster/lodestone-news/blob/master/.github/workflows/auto-approve.yml#L11](https://github.com/AwesomeHamster/lodestone-news/blob/master/.github/workflows/auto-approve.yml?rgh-link-date=2022-09-13T03%3A05%3A27Z#L11)
> 
> Looks like should you fire an issue in that repository either. >_<

https://github.com/AwesomeHamster/koishi-plugin-hitokoto/blob/master/.github/workflows/auto-approve.yml#L12

**Comment by MaikoTan** [comment]
> > Looks like should you fire an issue in that repository either. >_<
> 
> [https://github.com/AwesomeHamster/koishi-plugin-hitokoto/blob/master/.github/workflows/auto-approve.yml#L12](https://github.com/AwesomeHamster/koishi-plugin-hitokoto/blob/master/.github/workflows/auto-approve.yml?rgh-link-date=2022-09-13T03%3A09%3A37Z#L12)

Ok, you fire it either...
